#ifndef RPL_HPP
# define RPL_HPP

#define RPL_WELCOME " 001 "
#define ERR_NOSUCHNICK " 401 "
#define ERR_CANNOTSENDTOCHAN " 404 "
#define ERR_NORECIPIENT " 411 "
#define ERR_NOTEXTTOSEND " 412 "
#define ERR_NONICKNAMEGIVEN " 431 "
#define ERR_ERRONEUSNICKNAME " 432 "
#define ERR_NICKNAMEINUSE " 433 "

#define RPL_NAMREPLY			" 353 "
#define RPL_ENDOFNAMES			" 366 "



#endif
